/**
 * Convenience exports for filters (WordPress-like).
 */
export { registerFilter, applyFilters } from "./index.ts";

/**
 * Lista de filtros de WordPress (nombres originales) para compatibilidad/documentación.
 * Puedes mapearlos a prefijo cms_ usando `toCmsFilterName`.
 */
export const WORDPRESS_FILTERS: string[] = [
  // Post, Page, Attachment (lectura)
  "attachment_fields_to_edit",
  "attachment_icon",
  "attachment_innerHTML",
  "author_edit_pre",
  "body_class",
  "content_edit_pre",
  "content_filtered_edit_pre",
  "excerpt_edit_pre",
  "date_edit_pre",
  "date_gmt_edit_pre",
  "get_attached_file",
  "get_enclosed",
  "get_pages",
  "get_pung",
  "get_the_archive_title",
  "get_the_excerpt",
  "get_the_guid",
  "get_to_ping",
  "icon_dir",
  "icon_dir_uri",
  "image_size_names_choose",
  "mime_type_edit_pre",
  "modified_edit_pre",
  "modified_gmt_edit_pre",
  "no_texturize_shortcodes",
  "parent_edit_pre",
  "password_edit_pre",
  "post_class",
  "pre_kses",
  "prepend_attachment",
  "protected_title_format",
  "private_title_format",
  "sanitize_title",
  "single_post_title",
  "status_edit_pre",
  "the_content",
  "the_content_rss",
  "the_content_feed",
  "the_editor_content",
  "the_excerpt",
  "the_excerpt_rss",
  "the_password_form",
  "the_tags",
  "the_title",
  "the_title_rss",
  "title_edit_pre",
  "type_edit_pre",
  "wp_dropdown_pages",
  "wp_list_pages",
  "wp_list_pages_excludes",
  "wp_get_attachment_metadata",
  "wp_get_attachment_thumb_file",
  "wp_get_attachment_thumb_url",
  "wp_get_attachment_url",
  "wp_mime_type_icon",
  "wp_title",
  // Post, Page, Attachment (escritura)
  "add_ping",
  "attachment_fields_to_save",
  "attachment_max_dims",
  "category_save_pre",
  "comment_status_pre",
  "content_filtered_save_pre",
  "content_save_pre",
  "excerpt_save_pre",
  "image_save_pre",
  "jpeg_quality",
  "name_save_pre",
  "phone_content",
  "ping_status_pre",
  "post_mime_type_pre",
  "status_save_pre",
  "thumbnail_filename",
  "title_save_pre",
  "update_attached_file",
  "wp_create_thumbnail",
  "wp_delete_file",
  "wp_generate_attachment_metadata",
  "wp_save_image_file",
  "wp_thumbnail_creation_size_limit",
  "wp_thumbnail_max_side_length",
  "wp_update_attachment_metadata",
  // Comentarios (lectura)
  "comment_excerpt",
  "comment_flood_filter",
  "comment_post_redirect",
  "comment_text",
  "comment_text_rss",
  "comments_array",
  "comments_number",
  "get_comment_excerpt",
  "get_comment_ID",
  "get_comment_text",
  "get_comment_type",
  "get_comments_number",
  "post_comments_feed_link",
  // Comentarios (escritura)
  "comment_save_pre",
  "pre_comment_approved",
  "pre_comment_content",
  "preprocess_comment",
  "wp_insert_post_data",
  // Categorías y términos (lectura)
  "category_description",
  "category_feed_link",
  "category_link",
  "get_ancestors",
  "get_categories",
  "get_category",
  "list_cats",
  "list_cats_exclusions",
  "single_cat_title",
  "the_category",
  "the_category_rss",
  "wp_dropdown_cats",
  "wp_list_categories",
  "wp_get_object_terms",
  // Categorías y términos (escritura)
  "pre_category_description",
  "wp_update_term_parent",
  "edit_terms",
  "pre_category_name",
  "pre_category_nicename",
  // Links
  "attachment_link",
  "author_feed_link",
  "author_link",
  "comment_reply_link",
  "day_link",
  "feed_link",
  "get_comment_author_link",
  "get_comment_author_url_link",
  "month_link",
  "page_link",
  "post_link",
  "post_type_link",
  "the_permalink",
  "year_link",
  "tag_link",
  "term_link",
  // Fechas y tiempo
  "get_comment_date",
  "get_comment_time",
  "get_the_modified_date",
  "get_the_modified_time",
  "get_the_time",
  "the_date",
  "the_modified_date",
  "the_modified_time",
  "the_time",
  "the_weekday",
  "the_weekday_date",
  // Usuario/autor (lectura)
  "login_body_class",
  "login_redirect",
  "user_contactmethods",
  "update_(meta_type)_metadata",
  "author_email",
  "comment_author",
  "comment_author_rss",
  "comment_email",
  "comment_url",
  "get_comment_author",
  "get_comment_author_email",
  "get_comment_author_IP",
  "get_comment_author_url",
  "login_errors",
  "login_headertitle",
  "login_headerurl",
  "login_message",
  "role_has_cap",
  "sanitize_user",
  "the_author",
  "the_author_email",
  "user_search_columns",
  // Usuario/autor (escritura)
  "pre_comment_author_email",
  "pre_comment_author_name",
  "pre_comment_author_url",
  "pre_comment_user_agent",
  "pre_comment_user_ip",
  "pre_user_id",
  "pre_user_description",
  "pre_user_display_name",
  "pre_user_email",
  "pre_user_first_name",
  "pre_user_last_name",
  "pre_user_login",
  "pre_user_nicename",
  "pre_user_nickname",
  "pre_user_url",
  "registration_errors",
  "user_registration_email",
  "validate_username",
  // Blogroll
  "get_bookmarks",
  "link_category",
  "link_description",
  "link_rating",
  "link_title",
  "pre_link_description",
  "pre_link_image",
  "pre_link_name",
  "pre_link_notes",
  "pre_link_rel",
  "pre_link_rss",
  "pre_link_target",
  "pre_link_url",
  // Blog info / options
  "all_options",
  "all_plugins",
  "bloginfo",
  "bloginfo_rss",
  "bloginfo_url",
  "loginout",
  "lostpassword_url",
  "option_(option name)",
  "pre_get_space_used",
  "pre_option_(option name)",
  "pre_update_option_(option name)",
  "register",
  "upload_dir",
  "upload_mimes",
  // Texto
  "attribute_escape",
  "js_escape",
  "sanitize_key",
  // Administración
  "admin_user_info_links",
  "autosave_interval",
  "bulk_actions",
  "bulk_post_updated_messages",
  "cat_rows",
  "comment_edit_pre",
  "comment_edit_redirect",
  "comment_moderation_subject",
  "comment_moderation_text",
  "comment_notification_headers",
  "comment_notification_subject",
  "comment_notification_text",
  "comment_row_actions",
  "cron_request",
  "cron_schedules",
  "custom_menu_order",
  "default_content",
  "default_excerpt",
  "default_title",
  "editable_slug",
  "format_to_edit",
  "format_to_post",
  "manage_edit-${post_type}_columns",
  "manage_link-manager_columns",
  "manage_posts_columns",
  "manage_pages_columns",
  "manage_users_columns",
  "manage_users_custom_column",
  "manage_users_sortable_columns",
  "media_row_actions",
  "menu_order",
  "nonce_life",
  "nonce_user_logged_out",
  "plugin_row_meta",
  "postmeta_form_limit",
  "post_row_actions",
  "post_updated_messages",
  "pre_upload_error",
  "preview_page_link",
  "preview_post_link",
  "richedit_pre",
  "schedule_event",
  "set-screen-option",
  "show_password_fields",
  "terms_to_edit",
  "the_editor",
  "user_can_richedit",
  "user_has_cap",
  "wp_handle_upload_prefilter",
  "wp_handle_upload",
  "wp_revisions_to_keep",
  "wp_terms_checklist_args",
  "wp_upload_tabs",
  "media_upload_tabs",
  "plugin_action_links_(plugin file name)",
  "views_edit-post",
  // Editor
  "mce_spellchecker_languages",
  "mce_buttons",
  "mce_buttons_2",
  "mce_buttons_3",
  "mce_buttons_4",
  "mce_css",
  "mce_external_plugins",
  "mce_external_languages",
  "tiny_mce_before_init",
  // Templates/temas
  "locale_stylesheet_uri",
  "stylesheet",
  "stylesheet_directory",
  "stylesheet_directory_uri",
  "stylesheet_uri",
  "template",
  "template_directory",
  "template_directory_uri",
  "theme_root",
  "theme_root_uri",
  "404_template",
  "archive_template",
  "attachment_template",
  "author_template",
  "category_template",
  "comments_popup_template",
  "comments_template",
  "date_template",
  "home_template",
  "page_template",
  "paged_template",
  "search_template",
  "single_template",
  "shortcut_link",
  "template_include",
  "wp_nav_menu_args",
  "wp_nav_menu_items",
  // Kubrick (legacy)
  "kubrick_header_color",
  "kubrick_header_display",
  "kubrick_header_image",
  // Login/registro
  "authenticate",
  "wp_authenticate_user",
  "registration_errors", // (duplicada en user section)
  "user_registration_email", // (duplicada en user section)
  "validate_username", // (duplicada en user section)
  // Redirect/Rewrite
  "allowed_redirect_hosts",
  "author_rewrite_rules",
  "category_rewrite_rules",
  "comments_rewrite_rules",
  "date_rewrite_rules",
  "mod_rewrite_rules",
  "page_rewrite_rules",
  "post_rewrite_rules",
  "redirect_canonical",
  "rewrite_rules_array",
  "root_rewrite_rules",
  "search_rewrite_rules",
  "wp_redirect",
  "wp_redirect_status",
  // WP_Query
  "found_posts",
  "found_posts_query",
  "post_limits",
  "posts_clauses",
  "posts_distinct",
  "posts_fields",
  "posts_groupby",
  "posts_join",
  "posts_join_paged",
  "posts_orderby",
  "posts_request",
  "posts_results",
  "posts_search",
  "posts_where",
  "posts_where_paged",
  "the_posts",
  // Media
  "editor_max_image_size",
  "image_downsize",
  "get_image_tag_class",
  "get_image_tag",
  "image_resize_dimensions",
  "intermediate_image_sizes",
  "wp_get_attachment_image_attributes",
  "img_caption_shortcode",
  "post_gallery",
  "use_default_gallery_style",
  "gallery_style",
  "adjacent_image_link",
  "embed_defaults",
  "load_default_embeds",
  "embed_oembed_html",
  "embed_googlevideo",
  "oembed_result",
  "upload_size_limit",
  "wp_image_editors",
  "plupload_default_settings",
  "plupload_default_params",
  "image_size_names_choose", // (duplicada arriba)
  "wp_prepare_attachment_for_js",
  "media_upload_tabs", // (duplicada admin)
  "disable_captions",
  "media_view_settings",
  "media_view_strings",
  "wp_handle_upload_prefilter", // (duplicada admin)
  // Advanced/internacionalización
  "create_user_query",
  "get_editable_authors",
  "get_next_post_join",
  "get_next_post_sort",
  "get_next_post_where",
  "get_previous_post_join",
  "get_previous_post_sort",
  "get_previous_post_where",
  "gettext",
  "override_load_textdomain",
  "get_meta_sql",
  "get_others_drafts",
  "get_users_drafts",
  "locale",
  "query",
  "query_string",
  "query_vars",
  "request",
  "excerpt_length",
  "excerpt_more",
  "post_edit_form_tag",
  "update_user_query",
  "uploading_iframe_src",
  "xmlrpc_methods",
  "wp_mail_from",
  "wp_mail_from_name",
  "update_(meta_type)_metadata", // (duplicada)
  // Widgets
  "dynamic_sidebar_params",
  "widget_archives_dropdown_args",
  "widget_categories_args",
  "widget_links_args",
  "widget_nav_menu_args",
  "widget_pages_args",
  "widget_tag_cloud_args",
  "widget_text",
  "widget_title",
];

/**
 * Convierte un filtro WP a nombre con prefijo cms_ (normalizado).
 */
export function toCmsFilterName(wpFilter: string): string {
  const cleaned = wpFilter.replace(/[^\w]+/g, "_").replace(/_+/g, "_").replace(/^_|_$/g, "");
  return `cms_${cleaned}`;
}

/**
 * Registra un filtro usando el nombre WP original; se mapea a prefijo cms_.
 */
export function registerWpFilter(hook: string, handler: (...args: any[]) => any, priority = 10, name?: string) {
  const cmsName = toCmsFilterName(hook);
  registerFilter(cmsName, handler, priority, name ?? hook);
}

/**
 * Aplica filtros usando nombre WP original; se mapea a prefijo cms_.
 */
export async function applyWpFilters<T = any>(hook: string, value: T, ...args: any[]): Promise<T> {
  const cmsName = toCmsFilterName(hook);
  return applyFilters(cmsName, value, ...args);
}
